apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift-online/rosa-agent?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main" && (
      "Containerfile".pathChanged() ||
      "sandbox/***".pathChanged() ||
      "policies/***".pathChanged() ||
      "provider-profiles/***".pathChanged() ||
      ".tekton/rosa-agent-push.yaml".pathChanged() ||
      ".tekton/rosa-agent-pull-request.yaml".pathChanged() ||
      ".tekton/pipeline-build-image.yaml".pathChanged()
      )
  creationTimestamp:
  labels:
    appstudio.openshift.io/application: rosa-agent
    appstudio.openshift.io/component: rosa-agent
    pipelines.appstudio.openshift.io/type: build
  name: rosa-agent-on-push
  namespace: rosa-tenant
spec:
  pipelineRef:
    name: rosa-agent-build-image
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rosa-tenant/rosa-agent:{{revision}}
  - name: build-platforms
    value:
    - linux/x86_64
    - linux/arm64
  - name: dockerfile
    value: Containerfile
  taskRunTemplate:
    serviceAccountName: build-pipeline-rosa-agent
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
